name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f restApp/requirements.txt ]; then pip install -r restApp/requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        for file in $(git ls-files '*.py'); do
          if file "$file" | grep -q "with BOM"; then
            sed -i '1s/^\xEF\xBB\xBF//' "$file"
          fi
        done
        pylint $(git ls-files '*.py')
      

